### PR TITLE
Optional mobile images

### PR DESCRIPTION
**Pull request by xendk**
New optional module for separate images for mobile site. Some Features cleanup had to be done.

### CODE REVIEW

**Comment by kasperg** [comment]
Looks good to me.

Happy about the feature cleanup - especially [removing handlers already defined elsewhere](https://github.com/dingproject/ding-mobile/pull/1/files#L14L294).

If this is merged, we should also include [alternator PR #2](https://github.com/dingproject/alternator/pull/2).

@cableman?

**Comment by cableman** [comment]
I think it's a good idea with a field for mobile images, as the scaling "always" makes the image look ugly. 

But I am not a fan of the views_alter in ding_mobile_images.module as it makes it hard to figure out where the mobile image is used from inside views UI (you have to known that the alter exists). Is the alter used to save an extra views display/panel ?

**Comment by kasperg** [comment]
As I understand it using the alter should mean that Views UI shows the mobile image field instead of the normal listing image field.

The only other option I see for implementing this would be to implement new views and variants for the panels. This would increase complexity and make it hard to combine mobile images with other extensions to Ding Mobile.

Can the problem be alleviated with some documentation?

**Comment by cableman** [comment]
Adding this information to the modules readme would be a good solution (maybe one that we should apply in all the repositories). :-)

If we make it a habit to write these anomalies into the readme's/development text files, it could be the first place to look when things misbehave.

**Comment by kasperg** [comment]
Agreed. This is stuff for the Ding Coding Standards.

Would you accept the current contribution if a readme was added with a note describing this?

**Comment by cableman** [comment]
Yes, just add it to the read me :-)

**Comment by kasperg** [comment]
I've asked @xendk to add a README file.

**Comment by xendk** [comment]
Note that views shows the altered view, so that an un-overridden view will show the use of mobile_image.

**Comment by xendk** [comment]
There?

**Pull request merged**
